// ============================================================
// EASYCOM SUISSE — BASE PRODUITS
// Pour modifier : éditez ce fichier et rechargez le site
// Affiliate Amazon ID : easycom0-21
// ============================================================

const AMAZON_ID = 'easycom0-21';

const PRODUCTS = [
  {
    id: 1,
    cat: 'earbuds',
    icon: '🎧',
    badge: 'BESTSELLER',
    name_fr: 'TransEar Pro X1',
    name_en: 'TransEar Pro X1',
    type_fr: 'Oreillette IA',
    type_en: 'AI Earbuds',
    desc_fr: 'Traduction simultanée en temps réel dans 40+ langues. Bluetooth 5.3, autonomie 8h, étanche IPX5. Compatible iOS & Android.',
    desc_en: 'Real-time simultaneous translation in 40+ languages. Bluetooth 5.3, 8h battery, IPX5 waterproof. iOS & Android compatible.',
    price_eur: 89,
    price_chf: 89,
    margin_pct: 65,
    supplier: 'Alibaba',
    supplier_url: 'https://alibaba.com',
    delivery_fr: '7-14 jours',
    delivery_en: '7-14 days',
    amazon_asin: 'B0XXXXXX01',
    amazon_url: 'https://www.amazon.fr/dp/B0XXXXXX01?tag=easycom0-21',
    mda: true,
    stock: 'dropship',
    rating: 4.7,
    reviews: 234,
    images: ['🎧']
  },
  {
    id: 2,
    cat: 'earbuds',
    icon: '🎧',
    badge: 'NOUVEAU',
    name_fr: 'LinguaPods Elite',
    name_en: 'LinguaPods Elite',
    type_fr: 'Écouteurs Traducteurs',
    type_en: 'Translation Earphones',
    desc_fr: 'Son Hi-Fi audiophile + traduction IA. Réduction de bruit active, recharge sans fil 15W, 6h + 24h boîtier.',
    desc_en: 'Hi-Fi audiophile sound + AI translation. Active noise cancellation, 15W wireless charging, 6h + 24h case.',
    price_eur: 129,
    price_chf: 129,
    margin_pct: 70,
    supplier: 'CJDropshipping',
    supplier_url: 'https://cjdropshipping.com',
    delivery_fr: '5-10 jours',
    delivery_en: '5-10 days',
    amazon_asin: 'B0XXXXXX02',
    amazon_url: 'https://www.amazon.fr/dp/B0XXXXXX02?tag=easycom0-21',
    mda: true,
    stock: 'dropship',
    rating: 4.5,
    reviews: 187,
    images: ['🎧']
  },
  {
    id: 3,
    cat: 'scanner',
    icon: '🖱️',
    badge: 'PRO',
    name_fr: 'ScanMouse Translate 3000',
    name_en: 'ScanMouse Translate 3000',
    type_fr: 'Souris Scanner',
    type_en: 'Scanner Mouse',
    desc_fr: 'Scan et traduction instantanée de textes physiques. 300 dpi, 112 langues, compatible Word/Excel/PDF. Idéal professions juridiques.',
    desc_en: 'Instant scan and translation of physical text. 300 dpi, 112 languages, Word/Excel/PDF compatible. Ideal for legal professions.',
    price_eur: 149,
    price_chf: 149,
    margin_pct: 75,
    supplier: 'Alibaba',
    supplier_url: 'https://alibaba.com',
    delivery_fr: '10-18 jours',
    delivery_en: '10-18 days',
    amazon_asin: 'B0XXXXXX03',
    amazon_url: 'https://www.amazon.fr/dp/B0XXXXXX03?tag=easycom0-21',
    mda: true,
    stock: 'dropship',
    rating: 4.6,
    reviews: 312,
    images: ['🖱️']
  },
  {
    id: 4,
    cat: 'glasses',
    icon: '🥽',
    badge: 'EXCLUSIF',
    name_fr: 'VisionTranslate AR',
    name_en: 'VisionTranslate AR',
    type_fr: 'Lunettes Traductrices AR',
    type_en: 'AR Translation Glasses',
    desc_fr: 'Affichage HUD en réalité augmentée. Traduction superposée dans votre champ de vision. 15 langues, monture premium, 6h autonomie.',
    desc_en: 'HUD display in augmented reality. Translation overlaid in your field of vision. 15 languages, premium frame, 6h battery.',
    price_eur: 299,
    price_chf: 299,
    margin_pct: 80,
    supplier: 'Worldwide Brands',
    supplier_url: 'https://worldwidebrands.com',
    delivery_fr: '7-14 jours',
    delivery_en: '7-14 days',
    amazon_asin: null,
    amazon_url: null,
    mda: true,
    stock: 'dropship',
    rating: 4.3,
    reviews: 89,
    images: ['🥽']
  },
  {
    id: 5,
    cat: 'gps-kids',
    icon: '⌚',
    badge: 'FAMILLE',
    name_fr: 'KidsTrack Pro',
    name_en: 'KidsTrack Pro',
    type_fr: 'Montre GPS Enfant',
    type_en: 'Kids GPS Watch',
    desc_fr: 'Géolocalisation temps réel, appel SOS bidirectionnel, zone de sécurité configurable, étanche 50m. Pour enfants 3-12 ans.',
    desc_en: 'Real-time geolocation, 2-way SOS call, configurable safety zone, waterproof 50m. For children aged 3-12.',
    price_eur: 79,
    price_chf: 79,
    margin_pct: 60,
    supplier: 'Spocket',
    supplier_url: 'https://spocket.co',
    delivery_fr: '5-8 jours',
    delivery_en: '5-8 days',
    amazon_asin: 'B0XXXXXX05',
    amazon_url: 'https://www.amazon.fr/dp/B0XXXXXX05?tag=easycom0-21',
    mda: true,
    stock: 'dropship',
    rating: 4.8,
    reviews: 567,
    images: ['⌚']
  },
  {
    id: 6,
    cat: 'gps-kids',
    icon: '⌚',
    badge: '4G',
    name_fr: 'SmartKid 4G Vidéo',
    name_en: 'SmartKid 4G Video',
    type_fr: 'Montre Enfant 4G',
    type_en: '4G Kids Watch',
    desc_fr: 'Vidéo appel HD, 4G/LTE, podomètre, réveil, appareil photo 2MP, résistant aux chocs. Nano-SIM incluse 3 mois.',
    desc_en: 'HD video call, 4G/LTE, pedometer, alarm, 2MP camera, shockproof. 3-month nano-SIM included.',
    price_eur: 109,
    price_chf: 109,
    margin_pct: 65,
    supplier: 'CJDropshipping',
    supplier_url: 'https://cjdropshipping.com',
    delivery_fr: '5-10 jours',
    delivery_en: '5-10 days',
    amazon_asin: 'B0XXXXXX06',
    amazon_url: 'https://www.amazon.fr/dp/B0XXXXXX06?tag=easycom0-21',
    mda: true,
    stock: 'dropship',
    rating: 4.4,
    reviews: 203,
    images: ['⌚']
  },
  {
    id: 7,
    cat: 'tracker',
    icon: '📡',
    badge: 'SLIM',
    name_fr: 'MagTracker Slim',
    name_en: 'MagTracker Slim',
    type_fr: 'Traceur GPS Magnétique',
    type_en: 'Magnetic GPS Tracker',
    desc_fr: 'Traceur ultra-fin magnétique. Voitures, bagages, animaux. 12 mois SIM data inclus. Alertes temps réel par SMS et app.',
    desc_en: 'Ultra-slim magnetic tracker. Cars, luggage, pets. 12-month data SIM included. Real-time SMS and app alerts.',
    price_eur: 59,
    price_chf: 59,
    margin_pct: 55,
    supplier: 'Alibaba',
    supplier_url: 'https://alibaba.com',
    delivery_fr: '10-20 jours',
    delivery_en: '10-20 days',
    amazon_asin: 'B0XXXXXX07',
    amazon_url: 'https://www.amazon.fr/dp/B0XXXXXX07?tag=easycom0-21',
    mda: true,
    stock: 'dropship',
    rating: 4.5,
    reviews: 445,
    images: ['📡']
  },
  {
    id: 8,
    cat: 'tracker',
    icon: '📡',
    badge: 'PET',
    name_fr: 'PetTrack Collar GPS',
    name_en: 'PetTrack Collar GPS',
    type_fr: 'Traceur GPS Animaux',
    type_en: 'Pet GPS Tracker',
    desc_fr: 'Collier GPS pour chien et chat. Étanche IP67, zone de sécurité, historique de parcours, batterie 7 jours.',
    desc_en: 'GPS collar for dogs and cats. IP67 waterproof, safety zone, route history, 7-day battery.',
    price_eur: 49,
    price_chf: 49,
    margin_pct: 58,
    supplier: 'Spocket',
    supplier_url: 'https://spocket.co',
    delivery_fr: '5-8 jours',
    delivery_en: '5-8 days',
    amazon_asin: 'B0XXXXXX08',
    amazon_url: 'https://www.amazon.fr/dp/B0XXXXXX08?tag=easycom0-21',
    mda: true,
    stock: 'dropship',
    rating: 4.6,
    reviews: 321,
    images: ['📡']
  },
  {
    id: 9,
    cat: 'android',
    icon: '📱',
    badge: 'TOURISTE',
    name_fr: 'TravelTab Pro 10"',
    name_en: 'TravelTab Pro 10"',
    type_fr: 'Tablette Android Touriste',
    type_en: 'Tourist Android Tablet',
    desc_fr: 'Tablette 10" préconfigurée : 50 langues de traduction, cartes offline 180 pays, SIM internationale 30j, guide touristique IA.',
    desc_en: '10" pre-configured tablet: 50 translation languages, offline maps 180 countries, 30-day international SIM, AI tourist guide.',
    price_eur: 199,
    price_chf: 199,
    margin_pct: 70,
    supplier: 'Worldwide Brands',
    supplier_url: 'https://worldwidebrands.com',
    delivery_fr: '7-14 jours',
    delivery_en: '7-14 days',
    amazon_asin: null,
    amazon_url: null,
    mda: true,
    stock: 'dropship',
    rating: 4.5,
    reviews: 156,
    images: ['📱']
  },
  {
    id: 10,
    cat: 'android',
    icon: '📱',
    badge: 'COMPACT',
    name_fr: 'TravelPhone Duo SIM',
    name_en: 'TravelPhone Duo SIM',
    type_fr: 'Smartphone Voyageur',
    type_en: 'Traveler Smartphone',
    desc_fr: 'Smartphone débloqué Dual SIM. Traduction vocale hors ligne, WiFi calling, batterie 6000mAh. 32 langues préinstallées.',
    desc_en: 'Unlocked Dual SIM smartphone. Offline voice translation, WiFi calling, 6000mAh battery. 32 pre-installed languages.',
    price_eur: 159,
    price_chf: 159,
    margin_pct: 65,
    supplier: '1688.com',
    supplier_url: 'https://1688.com',
    delivery_fr: '12-20 jours',
    delivery_en: '12-20 days',
    amazon_asin: 'B0XXXXXX10',
    amazon_url: 'https://www.amazon.fr/dp/B0XXXXXX10?tag=easycom0-21',
    mda: true,
    stock: 'dropship',
    rating: 4.3,
    reviews: 98,
    images: ['📱']
  }
];

const CATEGORIES = [
  { id: 'all',      icon: '🌐', label_fr: 'Tous les produits', label_en: 'All products' },
  { id: 'earbuds',  icon: '🎧', label_fr: 'Oreillettes & Écouteurs', label_en: 'Earbuds & Earphones' },
  { id: 'scanner',  icon: '🖱️', label_fr: 'Souris Scanners', label_en: 'Scanner Mice' },
  { id: 'glasses',  icon: '🥽', label_fr: 'Lunettes Traductrices', label_en: 'Translation Glasses' },
  { id: 'gps-kids', icon: '⌚', label_fr: 'Montres GPS Enfants', label_en: 'Kids GPS Watches' },
  { id: 'tracker',  icon: '📡', label_fr: 'Traceurs GPS', label_en: 'GPS Trackers' },
  { id: 'android',  icon: '📱', label_fr: 'Androids Touristes', label_en: 'Tourist Androids' }
];

// SITE CONFIG — à modifier selon vos besoins
const CONFIG = {
  site_name: 'EasyCom Suisse',
  email: 'contact@easycom.ch',
  amazon_id: 'easycom0-21',
  currency_primary: 'EUR',
  currency_secondary: 'CHF',
  vat_rate: 0.20,       // 20% TVA France
  vat_ch: 0.081,        // 8.1% TVA Suisse
  free_shipping_eur: 80, // Livraison gratuite à partir de
  stripe_pub_key: 'pk_live_VOTRE_CLE_STRIPE_ICI',
  paypal_client_id: 'VOTRE_CLIENT_ID_PAYPAL_ICI',
  whatsapp: '+41XXXXXXXXX',
  instagram: '@easycom.ch',
};
