// Catalogue ressources formation DJA.MAINT
// Toutes les ressources sont gratuites sauf mention contraire

const CATALOG = [
  // ─── Facility Management ─────────────────────────────────────────────────
  {
    id: 'ifma-ch',
    category: 'fm',
    title: 'IFMA Switzerland — Ressources FM',
    provider: 'IFMA',
    description: 'Association internationale FM : webinaires, guides, normes EN 15221. Membership gratuit en ligne.',
    url: 'https://www.ifma.ch',
    free: true,
    language: 'fr/de/en',
    format: 'Webinaires, documents',
  },
  {
    id: 'nfm-ch',
    category: 'fm',
    title: 'NFM Suisse — Normes et guides FM',
    provider: 'NFM Suisse',
    description: 'Ressources techniques FM suisses : gestion patrimoniale, exploitation, maintenance préventive.',
    url: 'https://www.nfm.ch',
    free: true,
    language: 'fr/de',
    format: 'Guides, normes',
  },
  {
    id: 'cfpa-ge',
    category: 'fm',
    title: 'CFPA Genève — Formation FM & bâtiment',
    provider: 'CFPA Genève',
    description: 'Centre de formation professionnelle des arts et métiers Genève. Cours bâtiment, maintenance, FM.',
    url: 'https://www.cfpa.ch',
    free: false,
    priceNote: 'Certaines formations subventionnées GE',
    language: 'fr',
    format: 'Cours présentiel/distanciel',
  },
  {
    id: 'youtube-fm',
    category: 'fm',
    title: 'Facility Management — Chaînes YouTube',
    provider: 'YouTube',
    description: 'HVAC School, The Engineering Mindset, Facility Management Association. Centaines de tutoriels gratuits.',
    url: 'https://www.youtube.com/@TheEngineeringMindset',
    free: true,
    language: 'en (sous-titres fr)',
    format: 'Vidéos',
  },
  {
    id: 'coursera-fm',
    category: 'fm',
    title: 'Facilities Management — University of Maryland',
    provider: 'Coursera',
    description: 'Cours universitaire complet FM : stratégie, opérations, durabilité. Audit gratuit disponible.',
    url: 'https://www.coursera.org/learn/facilities-management',
    free: true,
    priceNote: 'Audit gratuit (sans certificat)',
    language: 'en',
    format: 'MOOC en ligne',
  },

  // ─── Électrotechnique ─────────────────────────────────────────────────────
  {
    id: 'electrosuisse',
    category: 'elec',
    title: 'Electrosuisse — Normes et formation électrique',
    provider: 'Electrosuisse',
    description: 'Organisme suisse normes électriques. NIBT, installations BT, sécurité électrique. Formation continue.',
    url: 'https://www.electrosuisse.ch/fr/formation',
    free: false,
    priceNote: 'Certaines ressources gratuites',
    language: 'fr/de',
    format: 'Cours, normes, webinaires',
  },
  {
    id: 'openclassrooms-elec',
    category: 'elec',
    title: "Initiation à l'électrotechnique",
    provider: 'OpenClassrooms',
    description: "Bases de l'électricité, lois de Kirchhoff, circuits, sécurité. Niveau débutant à intermédiaire.",
    url: 'https://openclassrooms.com/fr/courses/5959771-initiez-vous-a-lelectronique-analogique',
    free: true,
    language: 'fr',
    format: 'MOOC en ligne',
  },
  {
    id: 'youtube-elec',
    category: 'elec',
    title: 'Électrotechnique — Chaînes YouTube FR',
    provider: 'YouTube',
    description: 'ScienceEtVie, Technique et Sciences, cours IUT électrotechnique complets et gratuits.',
    url: 'https://www.youtube.com/@ScienceEtVieTV',
    free: true,
    language: 'fr',
    format: 'Vidéos',
  },
  {
    id: 'khan-elec',
    category: 'elec',
    title: 'Electrical Engineering — Khan Academy',
    provider: 'Khan Academy',
    description: 'Cours complet circuits électriques, composants, analyse. Exercices interactifs.',
    url: 'https://fr.khanacademy.org/science/electrical-engineering',
    free: true,
    language: 'fr',
    format: 'MOOC interactif',
  },

  // ─── Normes ───────────────────────────────────────────────────────────────
  {
    id: 'sia-normes',
    category: 'normes',
    title: 'SIA — Normes construction et FM',
    provider: 'SIA (sia.ch)',
    description: 'Société suisse des ingénieurs et architectes. Normes SIA 118, 416, 2024, etc. essentielles en FM.',
    url: 'https://www.sia.ch/fr/normes/',
    free: false,
    priceNote: 'Normes payantes, résumés gratuits',
    language: 'fr/de',
    format: 'Documents techniques',
  },
  {
    id: 'suva-securite',
    category: 'normes',
    title: 'SUVA — Sécurité au travail',
    provider: 'SUVA',
    description: 'Documentation complète sécurité travaux FM : chutes, électricité, amiante, MSST. Tout gratuit.',
    url: 'https://www.suva.ch/fr-ch/prevention',
    free: true,
    language: 'fr',
    format: 'Guides, check-lists PDF',
  },
  {
    id: 'ofev-normes',
    category: 'normes',
    title: 'OFEV — Réglementation environnementale',
    provider: 'OFEV',
    description: 'Amiante, légionelle, déchets spéciaux, fluides frigorigènes. Obligations légales FM Suisse.',
    url: 'https://www.bafu.admin.ch/fr',
    free: true,
    language: 'fr',
    format: 'Guides réglementaires',
  },

  // ─── Gestion PME ──────────────────────────────────────────────────────────
  {
    id: 'hec-mooc',
    category: 'gestion',
    title: 'HEC Paris — MOOCs gestion PME',
    provider: 'HEC Paris / Coursera',
    description: "Comptabilité, finance d'entreprise, marketing, management. Certains audits gratuits.",
    url: 'https://www.coursera.org/hec',
    free: true,
    priceNote: 'Audit gratuit disponible',
    language: 'fr/en',
    format: 'MOOC en ligne',
  },
  {
    id: 'seco-pme',
    category: 'gestion',
    title: 'SECO — Ressources entrepreneur suisse',
    provider: 'SECO / Confédération',
    description: "Secrétariat d'État à l'économie : guides création, comptabilité, droit du travail, exportation.",
    url: 'https://www.seco.admin.ch/fr/accueil/PME.html',
    free: true,
    language: 'fr',
    format: 'Guides PDF, outils en ligne',
  },
  {
    id: 'kmu-admin',
    category: 'gestion',
    title: 'kmu.admin.ch — Portail PME Confédération',
    provider: 'Confédération suisse',
    description: 'Portail officiel PME : inscriptions RC, TVA, AVS, permis, modèles contrats, aides cantonales.',
    url: 'https://www.kmu.admin.ch/kmu/fr/home.html',
    free: true,
    language: 'fr',
    format: 'Portail services, guides',
  },
  {
    id: 'ge-pme',
    category: 'gestion',
    title: 'Genève PME — Soutien cantonal',
    provider: 'Canton de Genève',
    description: 'Service de promotion économique GE : accompagnement, financement, réseau. Spécifique Genève.',
    url: 'https://ge.ch/pme',
    free: true,
    language: 'fr',
    format: 'Conseil, financement',
  },
  {
    id: 'openclassrooms-gestion',
    category: 'gestion',
    title: 'Gérez vos finances avec Excel',
    provider: 'OpenClassrooms',
    description: 'Tableaux de bord, suivi trésorerie, comptabilité de base pour indépendants.',
    url: 'https://openclassrooms.com/fr/courses/5873811-gerez-votre-budget-avec-excel',
    free: true,
    language: 'fr',
    format: 'MOOC en ligne',
  },
];

const CATEGORIES = {
  fm:      { label: 'Facility Management', color: 'blue',   icon: '🏢' },
  elec:    { label: 'Électrotechnique',    color: 'yellow', icon: '⚡' },
  normes:  { label: 'Normes & Sécurité',  color: 'red',    icon: '📋' },
  gestion: { label: 'Gestion PME',         color: 'green',  icon: '📊' },
  autre:   { label: 'Autre',              color: 'gray',   icon: '📚' },
};

module.exports = { CATALOG, CATEGORIES };
